version: "3"

services:
  app:
    container_name: aplikasi-bootcamp
    image: ayocodingit/langkah-nyata-service:latest
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=sobat-takdir
      - APP_ENV=development
      - APP_PORT=3000
      - APP_KEY=KEY
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=db-app
      - JWT_SECRET=SECRET
    restart: always
    networks:
      - network_app

  mysql:
    container_name: database-bootcamp
    image: mysql:5.7.44
    volumes:
      - 'mysql_data:/data'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-app
    restart: always
    networks:
      - network_app

networks:
  network_app:
    driver: bridge

volumes:
  mysql_data: